# Generated by Django 3.1.5 on 2021-01-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='', max_length=8, verbose_name='Room ID')),
                ('access', models.BooleanField(verbose_name='Access')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Room Name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
