# Generated by Django 3.1.5 on 2021-01-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=7, verbose_name='Access'),
        ),
    ]
